<!--Do NOT change this file manually, it is being generated by svgicons script.-->

<template>
    <component v-bind:is="component"/>
</template>

<script>
    import startcase from 'lodash.startcase';
    import ArrowDown from '~/assets/svg/ico-arrow-down.svg?inline';
    import ArrowLeft from '~/assets/svg/ico-arrow-left.svg?inline';
    import ArrowRight from '~/assets/svg/ico-arrow-right.svg?inline';
    import ArrowUp from '~/assets/svg/ico-arrow-up.svg?inline';
    import Close from '~/assets/svg/ico-close.svg?inline';
    import Happy from '~/assets/svg/ico-happy.svg?inline';
    import QuoteLeft from '~/assets/svg/ico-quote-left.svg?inline';
    import QuoteRight from '~/assets/svg/ico-quote-right.svg?inline';

    export default {
        props: {
            iconName: {
                type: String,
                required: true
            }
        },
        components: {
            ArrowDown,
            ArrowLeft,
            ArrowRight,
            ArrowUp,
            Close,
            Happy,
            QuoteLeft,
            QuoteRight,

        },
        computed: {
            component() {
                return startcase(this.iconName.replace('ico-', '')).replace(' ', '');
            }
        }
    };
</script>
