name: starter
recipe: wordpress
proxy:
  appserver:
    - starter-admin.lndo.site

config:
  xdebug: true

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

  appserver:
    webroot: admin
    build_as_root:
      - a2enmod headers
    config:
      php: .lando/php.ini

  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
